// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // obj_control
global.__objectDepths[1] = 0; // obj_control_menu
global.__objectDepths[2] = 0; // obj_control_help
global.__objectDepths[3] = 0; // obj_control_settings
global.__objectDepths[4] = 0; // obj_control_about
global.__objectDepths[5] = 0; // obj_control_exit
global.__objectDepths[6] = 0; // obj_settings_rememberer
global.__objectDepths[7] = -7000; // obj_help_print
global.__objectDepths[8] = -7000; // obj_exit_print
global.__objectDepths[9] = -7000; // obj_about_print
global.__objectDepths[10] = -7000; // obj_settings_print
global.__objectDepths[11] = -1410065408; // obj_view
global.__objectDepths[12] = 0; // obj_collidable
global.__objectDepths[13] = 1000; // obj_floor
global.__objectDepths[14] = -1000000000; // obj_ceiling
global.__objectDepths[15] = -10000; // obj_ceiling2
global.__objectDepths[16] = -100000; // obj_wall
global.__objectDepths[17] = -100000; // obj_wall_building
global.__objectDepths[18] = -1000000; // obj_table
global.__objectDepths[19] = -1000000; // obj_pickup_machinegun
global.__objectDepths[20] = -1000000; // obj_pickup_pistol
global.__objectDepths[21] = -1000000; // obj_pickup_shotgun
global.__objectDepths[22] = 1000000; // obj_player
global.__objectDepths[23] = 0; // obj_zombie
global.__objectDepths[24] = 0; // obj_zombie_dead
global.__objectDepths[25] = 0; // obj_bullet
global.__objectDepths[26] = 0; // obj_hand_strike
global.__objectDepths[27] = -100000; // obj_hand
global.__objectDepths[28] = -100000; // obj_pistol
global.__objectDepths[29] = -100000; // obj_machinegun
global.__objectDepths[30] = -100000; // obj_shotgun
global.__objectDepths[31] = -6000; // obj_behak_about
global.__objectDepths[32] = -6000; // obj_behak_help
global.__objectDepths[33] = -6000; // obj_behak_settings
global.__objectDepths[34] = -6000; // obj_behak_exit
global.__objectDepths[35] = -9999; // obj_fade_menu_help
global.__objectDepths[36] = -9999; // obj_fade_help_settings
global.__objectDepths[37] = -9999; // obj_fade_help_about
global.__objectDepths[38] = -9999; // obj_fade_menu_exit
global.__objectDepths[39] = -9999; // obj_fade_menu
global.__objectDepths[40] = -9999; // obj_fade_help
global.__objectDepths[41] = -9999; // obj_fade_game
global.__objectDepths[42] = -8000; // obj_quitlogo
global.__objectDepths[43] = -8000; // obj_creditslogo
global.__objectDepths[44] = -8000; // obj_settingslogo
global.__objectDepths[45] = -8000; // obj_optionslogo
global.__objectDepths[46] = 0; // obj_tex_logo
global.__objectDepths[47] = -9000; // obj_tex_rootsoftlogo
global.__objectDepths[48] = -5000; // obj_screen
global.__objectDepths[49] = -8000; // obj_mud
global.__objectDepths[50] = -5000; // obj_pc
global.__objectDepths[51] = 150; // obj_menu_shadow
global.__objectDepths[52] = 100; // obj_tex_border_menu
global.__objectDepths[53] = 200; // obj_wow
global.__objectDepths[54] = 300; // object26
global.__objectDepths[55] = 200; // object30
global.__objectDepths[56] = 0; // spr_spr
global.__objectDepths[57] = 0; // spriterinoboj
global.__objectDepths[58] = -5000; // obj_arm_left
global.__objectDepths[59] = -9800; // obj_arm_right
global.__objectDepths[60] = -8500; // obj_menu


global.__objectNames[0] = "obj_control";
global.__objectNames[1] = "obj_control_menu";
global.__objectNames[2] = "obj_control_help";
global.__objectNames[3] = "obj_control_settings";
global.__objectNames[4] = "obj_control_about";
global.__objectNames[5] = "obj_control_exit";
global.__objectNames[6] = "obj_settings_rememberer";
global.__objectNames[7] = "obj_help_print";
global.__objectNames[8] = "obj_exit_print";
global.__objectNames[9] = "obj_about_print";
global.__objectNames[10] = "obj_settings_print";
global.__objectNames[11] = "obj_view";
global.__objectNames[12] = "obj_collidable";
global.__objectNames[13] = "obj_floor";
global.__objectNames[14] = "obj_ceiling";
global.__objectNames[15] = "obj_ceiling2";
global.__objectNames[16] = "obj_wall";
global.__objectNames[17] = "obj_wall_building";
global.__objectNames[18] = "obj_table";
global.__objectNames[19] = "obj_pickup_machinegun";
global.__objectNames[20] = "obj_pickup_pistol";
global.__objectNames[21] = "obj_pickup_shotgun";
global.__objectNames[22] = "obj_player";
global.__objectNames[23] = "obj_zombie";
global.__objectNames[24] = "obj_zombie_dead";
global.__objectNames[25] = "obj_bullet";
global.__objectNames[26] = "obj_hand_strike";
global.__objectNames[27] = "obj_hand";
global.__objectNames[28] = "obj_pistol";
global.__objectNames[29] = "obj_machinegun";
global.__objectNames[30] = "obj_shotgun";
global.__objectNames[31] = "obj_behak_about";
global.__objectNames[32] = "obj_behak_help";
global.__objectNames[33] = "obj_behak_settings";
global.__objectNames[34] = "obj_behak_exit";
global.__objectNames[35] = "obj_fade_menu_help";
global.__objectNames[36] = "obj_fade_help_settings";
global.__objectNames[37] = "obj_fade_help_about";
global.__objectNames[38] = "obj_fade_menu_exit";
global.__objectNames[39] = "obj_fade_menu";
global.__objectNames[40] = "obj_fade_help";
global.__objectNames[41] = "obj_fade_game";
global.__objectNames[42] = "obj_quitlogo";
global.__objectNames[43] = "obj_creditslogo";
global.__objectNames[44] = "obj_settingslogo";
global.__objectNames[45] = "obj_optionslogo";
global.__objectNames[46] = "obj_tex_logo";
global.__objectNames[47] = "obj_tex_rootsoftlogo";
global.__objectNames[48] = "obj_screen";
global.__objectNames[49] = "obj_mud";
global.__objectNames[50] = "obj_pc";
global.__objectNames[51] = "obj_menu_shadow";
global.__objectNames[52] = "obj_tex_border_menu";
global.__objectNames[53] = "obj_wow";
global.__objectNames[54] = "object26";
global.__objectNames[55] = "object30";
global.__objectNames[56] = "spr_spr";
global.__objectNames[57] = "spriterinoboj";
global.__objectNames[58] = "obj_arm_left";
global.__objectNames[59] = "obj_arm_right";
global.__objectNames[60] = "obj_menu";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for